### ISSUE TITLE
Cleanup Ansible code

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/ansible-quagga#2]
All aspects of this role need to be cleaned up for readability and formatting.

Example
--------
`tasks/debian.yml`
The following should be changed from this:
```
---
- name: debian | installing quagga pre-reqs
  apt: name={{ item }} state=present
  with_items:
    - lldpd
    - vlan

- name: debian | installing quagga
  apt: name=quagga state=present

- name: debian | enabling quagga
  service: name=quagga state=started enabled=yes
```
To this:
```
---
- name: debian | installing quagga pre-reqs
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'lldpd'
    - 'vlan'

- name: debian | installing quagga
  apt:
    name: "quagga"
    state: "present"

- name: debian | enabling quagga
  service:
    name: "quagga"
    state: "started"
    enabled: yes
```
